crud/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^add/$', views.add, name = 'add'),
    url(r'^delete/$', views.delete, name = 'delete'),
    url(r'^edit/(?P<editing_id>\d+)/$', views.edit, name = 'edit'),
]

guestboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    ]

hello/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.hello_world, name='hello_world'),
    url(r'^template/$', views.hello_template, name='hello_template'),
    url(r'^if/$', views.hello_if, name='hello_if'),
    url(r'^for/$', views.hello_for, name='hello_for'),
    url(r'^get/$', views.hello_get_query, name='hello_get_query'),
    url(r'^forms/$', views.hello_forms, name='hello_forms'),
    #url(r'^sample_forms/$', views.hello_sample_forms, name='hello_sample_forms'),
    url(r'^models/$', views.hello_models, name='hello_models'),
]

sandbox1st/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns = [
    url(r'^hello/', include('hello.urls', namespace = 'hello')),
    url(r'^crud/', include('crud.urls', namespace = 'crud')),
    url(r'^guestboard/', include('guestboard.urls', namespace='guestboard')),
]

crud/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    message = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return u"{0}:{1}...".format(self.id, self.message[:10])

guestboard/models.py
from django.db import models

# Create your models here.
class Posting(models.Model):
    name = models.CharField(
        max_length=64,
        verbose_name='名前',
        help_text='あなたの名前を入力してください',
        )
    message = models.CharField(
        max_length=255,
        verbose_name='メッセージ',
        help_text='メッセージを入力してください',
        )
    created_at = models.DateTimeField(
        auto_now_add = True,
        verbose_name='登録日時',
        )

hello/models.py
from django.db import models

# Create your models here.

class Hello(models.Model):
    your_name = models.CharField(max_length=10)
    
    def __str__(self):
        return "<{0}>".format(self.your_name)

crud/forms.py
from django import forms


class MessageForm(forms.Form):
    message = forms.CharField(
        label='メッセージ',
        max_length=255,
        required=True,
        widget=forms.TextInput()
        )

guestboard/forms.py
from django import forms
from .models import Posting


class PostingForm(forms.ModelForm):
    
    class Meta:
        model = Posting
        fields = ('name', 'message')
        widgets = {
            'name': forms.TextInput(attrs={'size': 40}),
            'message': forms.Textarea(attrs={'cols': 80, 'rows': 20})
            }
        

hello/forms.py
from django import forms


class HelloForm(forms.Form):
    your_name = forms.CharField(
        label = 'NAME',
        max_length=20,
        required=True,
        widget=forms.TextInput()
        )

crud/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
    )
from django.views.decorators.http import require_POST
from .models import Message
from .forms import MessageForm
# Create your views here.

def index(request):
    d = {
        'messages': Message.objects.all(),
        }
    return render(request, 'crud/index.html', d)


def add(request):
    form = MessageForm(request.POST or None)
    if form.is_valid():
        Message.objects.create(**form.cleaned_data)
        return redirect('crud:index')
    
    d = {
        'form': form,
        }
    return render(request, 'crud/edit.html', d)


def edit(request, editing_id):
    message = get_object_or_404(Message, id=editing_id)
    
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message.message = form.cleaned_data['message']
            message.save()
            return redirect('crud:index')
    else:
        #GETリクエスト時はDBに保存されているデータをFormに結びつける
        form = MessageForm({'message': message.message})
    
    d = {
        'form': form,
        }
    
    return render(request, 'crud/edit.html', d)


@require_POST
def delete(request):
    delete_ids = request.POST.getlist('delete_ids')
    if delete_ids:
        Message.objects.filter(id__in=delete_ids).delete()
    return redirect('crud:index')

guestboard/views.py
from django.core.paginator import (
    Paginator, #ページネーター本体のクラス
    EmptyPage, #ページ番号が範囲外だった場合に発生する例外クラス
    PageNotAnInteger #ページ番号が数字でなかった場合に発生する例外クラス
    )
from django.contrib import messages  # サンプルのページに存在していない。
from django.shortcuts import (
    render,
    redirect,
    )
from .models import Posting
from .forms import PostingForm
# Create your views here.

def _get_page(list_, page_no, count=5):
    """ページネーターを使い、表示するページ情報を取得する"""
    paginator = Paginator(list_, count)
    try:
        page = paginator.page(page_no)
    except (EmptyPage, PageNotAnInteger):
        # page_noが指定されていない場合、数値でない場合、範囲外の場合は先頭のページを報じする
        page = paginator.page(1)
    return page

def index(request):
    """表示、投稿を処理する"""
    # ModelFormもFormもインスタンスを作るタイミングでの使い方は同じ
    form = PostingForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            # save()メソッドを呼ぶだけでModelを使ってDBに登録される。
            form.save()
            # メッセージフレームワークを使い、処理が成功したことをユーザーに通知する
            messages.success(request, '投稿を受け付けました。')
            return redirect('guestboard:index')
        else:
            # メッセージフレームワークを使い、処理が失敗したことをユーザーに通知する
            messages.error(request, '入力内容に誤りがあります。')
    
    page = _get_page(
        Posting.objects.order_by('-id'),  # 投稿を新しい順に並び替えて所得する
        request.GET.get('page')           # GETクエリからページ番号を取得する
        )
    
    contexts = {
        'form': form,
        'page': page,
        }
    return render(request, 'guestboard/index.html', contexts)

hello/views.py
from django.shortcuts import render
# Create your views here.
from django.http.response import HttpResponse
from datetime import datetime

def hello_world(request):
    return HttpResponse('Hello World with django.')

# hello_template  ver.1
#def hello_template(request):
#    return render(request, 'index.html')
#

#v hello_template er.2
def hello_template(request):
    d = {
        'hour': datetime.now().hour,
        'message': 'Sample message',
        }
    return render(request, 'index.html', d)

def hello_if(request):
    d = {
        'is_visible': False,
        'empty_str': '',
        }
    return render(request, 'if.html', d)

def hello_for(request):
    d = {
        'objects': range(10),
        }
    return render(request, 'for.html', d)

def hello_get_query(request):
    d = {
        'your_name': request.GET.get('your_name')
        }
    return render(request, 'get_query.html', d)

from . import forms

def hello_forms(request):
    form = forms.HelloForm(request.GET or None)
    if form.is_valid():
        message = 'データ検証に成功しました'
    else:
        message = 'データ検証に失敗しました'
    
    d = {
        'form': form,
        'message': message,
        }
    return render(request, 'forms.html', d)

from django.shortcuts import redirect
from . import models

def hello_models(request):
    form = forms.HelloForm(request.POST or None)
    if form.is_valid():
        models.Hello.objects.create(**form.cleaned_data)
        return redirect('hello:hello_models')
    
    d = {
        'form': form,
        'hello_qs': models.Hello.objects.all().order_by('-id')
        }
    return render(request, 'models.html', d)

templates/base.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <title>Template extends sample</title>
</head>

<body>
  {% block body %}
  {% endblock %}
</block>
</html>

templates/crud/edit.html
{% extends "base.html" %}

{% block body %}
<a href="{% url 'crud:index' %}">一覧画面へ</a>
<form action="" method="post">
  {{ form.errors.message }}
  <label>{{ form.message.label }}{{ form.message }}</label><br/>
  {% csrf_token %}
  <input type="submit" value="登録">
</form>
{% endblock %}

templates/crud/index.html
{% extends "base.html" %}

{% block body %}
<a href="{% url 'crud:add' %}">登録画面へ</a>
<form method="post" action="{% url 'crud:delete' %}">
  <table border="1">
    <thead>
      <tr>
	<th> </th>
	<th>message</th>
	<th>created_at</th>
	<th>updated_at</th>
	<th> </th>
      </tr>
    </thead>
    <tbody>
      {% for message in messages %}
      <tr>
	<td><input type="checkbox" name="delete_ids" value="{{ message.id }}"></td>
	<td>{{ message.message }}</td>
	<td>{{ message.created_at }}</td>
	<td>{{ message.updated_at }}</td>
	<td><a href="{% url 'crud:edit' message.id %}">更新画面へ</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% csrf_token %}
  <input type="submit" value="削除">
</form>
{% endblock %}

templates/for.html
{% extends "base.html" %}

{% block body %}

{% for idx in objects %}
  {{ idx }}<br>
{% endfor %}

{% endblock %}

templates/for.not_extended.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <title>for and list sample</title>
</head>

<body>
  {% for idx in objects %}
    {{ idx }}<br>
  {% endfor %}
</body>
</html>

templates/forms.html
{% extends "base.html" %}

{% block body %}

  {{ message }}
  <hr>
  <form method="get" action="">
    
    {{ form.errors.your_name }}
    <label>{{ form.your_name.label }} {{ form.your_name }}</label><br>
    
    {{ form.errors.gender }}
    <label>{{ form.gender.label }} {{ form.gender }}</label><br>
    
    {{ form.errors.memo }}
    <label style="vertical-align: top;">{{ form.memo.label }} {{ form.memo }}</label><br>
    
    <input type="submit" value="Submit Buttom">
  </form>

{% endblock %}

templates/get_query.html
{% extends "base.html" %}

{% block body %}
  <form action="" method="get">
    <label>name:<input type="text" size="20" name="your_name"></label>
    <input type="submit" value="Submit Buttom">
  </form>
  {% if your_name %}
    {{ your_name }}さんこんにちは。
  {% endif %}
{% endblock %}

templates/guestboard/base.html
<!doctype html>
<html>
{% load staticfiles %}
<head lang="ja">
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% block css %}
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
  {% endblock %}
</head>
<body>
  <div class="container">
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    {% block body %}
    {% endblock %}
  </div>
  {% block js %}
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  {% endblock %}
</body>
</html>

templates/guestboard/index.html
{% extends "guestboard/base.html" %}
{% block title %}Guest Board{% endblock %}
{% block body %}
<div class="page-header">
  <h1>Guest Board</h1>
</div>

{# 画面上段 - 入力フォームを定義する #}
<form action="{% url 'guestboard:index' %}" method="post">
  <div class="row">
    {% for field in form %}
    <div class="form-group">
      {% if field.errors %}
      <div class="col-sm-10">
	<span class="col-sm-10">{{ field.errors }}</span>
      </div>
      {% endif %}
      <div class="col-sm-10">
	<label class="col-sm-3 control-label">{{ field.label_tag }}</label>
	<label class="label col-sm-7">{{ field }}</label>
      </div>
    </div>  {# form-group end #}
    {% endfor %}
    <div class="col-sm-10">
      <div class="form-group">
	<label class="col-sm-2 control-label"><input type="submit" class="btn btn-primary" value="登録"></label>
	{% csrf_token %}
      </div>
    </div>
  </div>  {# row end #}
</form>
<hr>

{# 画面下段 - 投稿内容とページネーター用のパーツを表示する #}
{% include "pagination.html" %}{# ページネーター用のパーツ #}
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      {% for posting in page %}
      <div class="panel panel-primary">
	<div class="panel-heading">
	  <h3 class="panel-title">{{ posting.name }} <label class="small">投稿日時：{{ posting.created_at }}</label></h3>
	</div>
	<div class="panel-body">
	  {{ posting.message }}
	</div>
      </div>  {# panel panel-primary end #}
      {% endfor %}
    </div>  {# col-sm-8 end #}
  </div>  {# row end #}
</div>  {# container end #}
{% include "pagination.html" %}{# ページネーター用のパーツ #}

{% endblock %}

templates/if.html
{% extends "base.html" %}

{% block body %}

{% if is_visible %}
  Show this 'cause is_visible is true,<br>
{% else %}
  Show this 'cause is_visible is false.<br>
{% endif %}

{% if empty_str|length > 0 %}
  the number of empty_str is {{ empty_str|length }} .
{% else %}
  empty_str is empty.<br>
{% endif %}

{% endblock %}

templates/if.not_extended.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <title>if sample</title>
</head>

<body>
  {% if is_visible %} Show this 'cause is_visible is true,<br>
  {% else %} Show this 'cause is_visible is false.<br>
  {% endif %}
  
  {% if empty_str|length > 0 %} the number of empty_str is {{ empty_str|length }} .
  {% else %} empty_str is empty.<br>
  {% endif %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}変数の練習{% endblock %}

{% block body %}
<div>
  {{ hour }}時です。<br>
  {{ message }}
</div>
<div>
  <a href="{% url 'hello:hello_world' %}">hello_world</a><br>
  <a href="{% url 'hello:hello_template' %}">template</a><br>
  <a href="{% url 'hello:hello_if' %}">if</a><br>
  <a href="{% url 'hello:hello_for' %}">for</a><br>
</div>
{% endblock %}

templates/index.ver.1.html
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Hello Template!
</body>
</html>

templates/index.ver.2.html
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title>Template Sample</title>
</head>
<body>
  {{ hour }}時です。<br>
  {{ message }}
</body>
</html>

templates/index.ver.3.html
{% extends "base.html" %}

{% block body %}
{{ hour }}時です。<br>
{{ message }}
{% endblock %}

templates/models.html
{% extends "base.html" %}

{% block body %}
  <h1>your_nameを登録する</h1>
  <h2>登録</h2>
  <form method="post" action="">
    {{ form.errors.your_name }}
    <label>{{ form.your_name.label }} {{ form.your_name }}</label><br>
    <input type="submit" value="送信">
    {% csrf_token %}
  </form>
  <hr>
  <h2>一覧</h2>
  {% for h in hello_qs %}
    {{ h.your_name }}<br>
  {% endfor %}
{% endblock %}

templates/pagination.html
{# ページネーター #}
<nav class="col-sm-8">
  <ul class="pager">
    
    {# ページ送りボタン(1) - 新しい投稿を表示する #}
    {% if page.has_previous %}
    <li class="previous">
      <a href="?page={{ page.previous_page_number }}"><span aria-hidden="true">&larr;</span> Newer</a>
    </li>
    {% else %}
    <li class="previous disabled">
      <a href="#"><span aria-hidden="true">&larr;</span> Newer</a>
    </li>
    {% endif %}
    
    {# ページ情報 #}
    <li>Page {{ page.number }} of {{ page.paginator.num_pages }}.</li>
    
    {# ページ送りボタン(2) - 古い投稿を表示する #}
    {% if page.has_next %}
    <li class="next">
      <a href="?page={{ page.next_page_number }}">Older <span aria-hidden="true">&rarr;</span></a>
    </li>
    {% else %}
    <li class="next disabled">
      <a href="#">Older <span aria-hidden="true">&rarr;</span></a>
    </li>
    {% endif %}
  
  </ul> {# class pager end #}
</nav>